build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "Personal Finance Tracker"
  org.opencontainers.image.description: "Personal finance tracking addon"
  org.opencontainers.image.source: "https://github.com/prapar2/ExpenseTracker"