name: "Personal Finance Tracker"
version: "1.0.14"
slug: "finance_tracker"
description: "Track personal income, expenses and savings across a financial year"
arch:
  - amd64
url: "https://github.com/prapar2/ExpenseTracker"
ingress: true
ingress_port: 3001
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: "Web UI"
ingress_entry: /
map:
  - type: data
    read_only: false
panel_icon: "mdi:currency-inr"
panel_title: "Finance Tracker"
startup: application
boot: auto
image: "ghcr.io/prapar2/finance-tracker-addon/{arch}"
init: false
